/**
 * ocurrences.js
 * 
 * Get hashtags generated by scraper.js and count its ocurrences and store them in a firebase database.
 */

var admin = require("firebase-admin");

var serviceAccount = require("./auth.json");
var databaseURL = require('./url.js');

// Firebase service auth.
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL
});

const db = admin.firestore();

// Existing hashtag collection generated by scraper.js.
const hashtags = db.collection('ocurrences');

const query = hashtags.get().then(snap => {
  console.log(snap.size);
});

