/**
 * sort.js
 * 
 * Get hashtags generated by scraper.js and count its ocurrences and store them in a firebase database.
 */

var admin = require("firebase-admin");
var databaseURL = require('./url.js');

var serviceAccount = require("./auth.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL
});

const db = admin.firestore();

const ocurrences = db.collection('ocurrences').orderBy('count', 'desc').limit(100);

const ranking = [];

const query = ocurrences.get()
    .then(snapshot => {
        snapshot.forEach(doc => {
            ranking.push(doc.data());
        });

        console.log(ranking);
        
    })
    .catch(err => {
        console.log('Error', err);
    });